repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co

helmfiles:
  - path: ingress-nginx/helmfile.yaml
  - path: kube-prometheus-stack/helmfile.yaml
  - path: grafana/helmfile.yaml
  - path: loki-stack/helmfile.yaml
  - path: elasticsearch/helmfile.yaml
