apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  labels:
    app: multitool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
        egress.monzo.com/allowed-reqbin: "true"
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          ports:
            - containerPort: 80
            - containerPort: 443
